ADD (8/23) 테스트 코드 작성하기
CodeSoom/spring-week3-assignment-1 pull request #32
Opened 2021-08-23 11:52 UTC by HyoungUkJJang

1. 강의 내용 참고하여 AssertJ와 MockMvc를 처음 사용해봤습니다.

--------------------------------------------------------------------------------

[계획]

* 테스트코드 작성이 처음이여서 오늘은 Junit과 AssertJ, Mockito에 대해 알아보고 정리하여  내일까지 작성하여 PR을 올릴 계획입니다.

2021-08-23 11:57 UTC, HyoungUkJJang commented
(8/23) 테스트코드 작성하기

* 이번주도 잘 부탁드리겠습니다 ! 혹독한 리뷰 부탁드립니다!!

1. 강의 내용 참고하여 AssertJ와 MockMvc를 처음 사용해봤습니다.
2. build.gradle 파일에 JPA implementaion 부분과 application.yml 파일의 JPA 설정 부분을 3주차 과제 내용에 포함되지 않는 부분인 것 같아 주석처리 하였습니다.


--------------------------------------------------------------------------------

[계획]

* 테스트코드 작성이 처음이여서 오늘은 Junit과 AssertJ, Mockito에 대해 알아보고 정리하여  내일까지 작성하여 PR을 올릴 계획입니다.

2021-08-23 12:19 UTC, johngrib reviewed
이번주도 열심히 학습해 봅시다. 화이팅!

2021-08-23 12:19 UTC, johngrib commented on app/build.gradle
> +//    runtimeOnly 'com.h2database:h2'
이렇게 주석 처리하는 것보다 시원하게 지워버리는 것이 더 좋을 수도 있어요. :-)

2021-08-23 12:19 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +
불필요한 변경입니다.

2021-08-23 12:19 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerTest.java
> +}
![image](https://user-images.githubusercontent.com/1855714/130445641-78be622a-7eb4-4254-aa9e-c9caef99dbd2.png)

파일 마지막에 개행 문자를 추가해 주세요.

다른 분 리뷰에 달아드린 코멘트를 함께 읽어 봅시다.
https://github.com/CodeSoom/spring-week1-assignment-1/pull/40#discussion_r685148029

2021-08-23 12:19 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +    @Test
`@DisplayName` 애노테이션을 사용해 이 테스트가 무엇을 위한 테스트인지를 설명해 보세요.

2021-08-24 11:53 UTC, HyoungUkJJang commented on app/build.gradle
> +//    runtimeOnly 'com.h2database:h2'
반영 하였습니다 !

2021-08-24 11:53 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +    @Test
반영 하였습니다 !

2021-08-24 11:53 UTC, HyoungUkJJang commented
(8/24) 피드백 반영 및 소스코드 작성

1. TaskServiceTest 클래스 작성
2. TaskControllerTest 클래스 작성
3. TaskTest 클래스 작성

—————————————————————————————————————————————————————

https://velog.io/@gudnr1451/Junit-AssertJ-%EA%B8%B0%EB%B3%B8%EC%A0%95%EB%A6%AC 

Junit과 AssertJ의 기본 메소드를 사용해보고 정리하면서 오늘은 AssertJ를 이용한 객체 테스트 코드를 작성하였습니다. 

—————————————————————————————————————————————————————

assertThat("test1").isEqualTo(detail.getTitle()); 

테스트 코드 작성시에도 equals를 이렇게 작성하나요??

—————————————————————————————————————————————————————

2021-08-24 12:20 UTC, johngrib commented
> (8/24) 피드백 반영 및 소스코드 작성
> 
> 1. TaskServiceTest 클래스 작성
> 2. TaskControllerTest 클래스 작성
> 3. TaskTest 클래스 작성
> 
> —————————————————————————————————————————————————————
> 
> https://velog.io/@gudnr1451/Junit-AssertJ-%EA%B8%B0%EB%B3%B8%EC%A0%95%EB%A6%AC
> 
> Junit과 AssertJ의 기본 메소드를 사용해보고 정리하면서 오늘은 AssertJ를 이용한 객체 테스트 코드를 작성하였습니다.
> 
> —————————————————————————————————————————————————————
> 
> assertThat("test1").isEqualTo(detail.getTitle());
> 
> 테스트 코드 작성시에도 equals를 이렇게 작성하나요??
> 
> —————————————————————————————————————————————————————

제 경우에는 `assertThat`을 쓰는 것보다 보통 `Assertions.assertEqual("test1", defail.getTitle());` 이렇게 쓰는 걸 선호합니다.

2021-08-24 12:25 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +   public TaskController(TaskService taskService) {
인덴트가 뭔가 조금 어긋났군요.

2021-08-24 12:25 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +    }
설명은 `전체조회`라고 되어 있어요. 그런데 실제로 테스트하는 내용은 `getTasks()`의 결과가 1개인지를 검사하고 있습니다. `TaskService`의 코드를 전혀 보지 않은 사람이 이 설명과 이 테스트 코드의 내용을 읽으면 과연 쉽게 이해할 수 있을까요?

2021-08-24 12:25 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +        assertThat("test1").isEqualTo(taskService.getTask(1L).getTitle());
`setUp`에 있는 `test1`을 실수로 `test2`로 수정하고, 여기에 있는 `detail`메소드에 있는 `test1`은 깜빡하고 수정하지 않았다고 가정해 봅시다. 어떤 문제가 있을까요?

2021-08-24 12:25 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +    }
설명을 읽어보면 `상세조회` 기능은 예외를 던지는 것이 정상적인 결과인 것 같습니다.

2021-08-25 12:11 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +    }
단순히 사이즈만 검증하는 테스트라 쉽게 이해할 수 없을것 같습니다. 테스트 케이스를 조금 더 추가하고 좋은 방법을 생각해 보겠습니다

2021-08-25 12:12 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +    private static final String TASK_TITLE_4 = "test4";
이런건 배열을 쓰는 것이 낫지 않을까요?

2021-08-25 12:12 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +        assertThat("test1").isEqualTo(taskService.getTask(1L).getTitle());
기대한 값과 실제 값이 다르게 나와 테스트가 실패하는 상황이 벌어질 것 같습니다. 
같은 값을 비교하여 테스트를 하는 경우에는 따로 private static final 변수로 생성하여 실수를 방지할 수 있을 것 같습니다.

2021-08-25 12:14 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +    private static final String TASK_TITLE_4 = "test4";
단순 이름 반복이기 때문에 배열이 더욱 보기 편할 것 같습니다. 수정하겠습니다

2021-08-25 12:52 UTC, HyoungUkJJang commented
(8/25)  피드백 반영 및 소스코드 수정

1. 피드백 반영
2. TaskServiceTest 소스코드 수정

------------------------------------------------------------------------------------------------------------------------

종립님의 블로그 글을 참고하면서 저도 한번 적용해봤습니다. 테스트 코드 작성이 처음이라 잘 한건지는 모르겠지만 구분을 지어주면서 작성하니까 보기도 좋고 재미도 있는것 같습니다. 더 연습해서 깔끔하게 작성해보도록 노력하겠습니다.

-------------------------------------------------------------------------------------------------------------------------

전체 조회에서 값이 없는 경우나 수정, 삭제 시에 해당 id값이 없는 경우에도 테스트 케이스를 추가하려고 하는데  테스트 코드에서 테스트 케이스는 많을수록 좋은건가요?

2021-08-28 11:55 UTC, HyoungUkJJang commented
(8/28) 피드백 반영 및 소스코드 수정

1. TaskServiceTest 피드백 반영하여 소스코드 수정
2. TaskControllerWebTest delete 메소드 소스코드 수정

-------------------------------------------------------------------------------------------------------------------------

부족하지만 정리를 해보면서 복습을 해봤습니다. 

* Junit & AssertJ 정리
https://velog.io/@gudnr1451/Junit-AssertJ-%EA%B8%B0%EB%B3%B8%EC%A0%95%EB%A6%AC

* Mock 정리
https://velog.io/@gudnr1451/Mockito-%EB%9E%80

-------------------------------------------------------------------------------------------------------------------------

[질문정리]

1. TaskService / TaskControllerTest 같은 경우를 보면 TaskControllerTest 클래스는 TaskService를 의존하여 테스트를 진행하는데 그렇다면 TaskControllerTest 클래스 파일 안에서 결국 TaskService 클래스도 같이 테스트가 적용되는게 아닌가? 라는 의문이 들었습니다. 두개 다 테스트 코드를 작성하는게 올바른 방법인 것 같은데 문득 검증하는 소스코드 유사한 면이 들었던 것 같습니다. 실무에서는 당연히 유사하다고 해도 두개의 클래스파일을 따로따로 테스트코드를 작성해주는 것이 맞는 방법이겠죠?

2. D-C-I 의 패턴을 적용하며 작성을 하다보니 계층적으로 볼 수 있어서 어디가 문제가 생겼는지 금방 확인이 가능한 것을 알 수 있었습니다. 하지만 그만큼 한 클래스파일에서 소스코드 라인 수가 길어지는 것을 느꼈습니다. 간단한 로직을 테스트 하는 경우에는 D-C-I패턴 말고 다른 방법을 사용하는게 나은 방법 일까요?   

3. TaskControllerWerbTest 소스코드에서는 소스코드를 잘 작성한건지 given메소드를 올바르게 사용했는지 피드백을 듣고싶습니다. 
    수정한 TaskService와 TaskServiceCotroller 파일에 좀 더 개선할 부분이 있는지 듣고싶어요 !
    확실히 assertEquals와 assertThat에 좀 익숙해 진 것 같습니다 !

-------------------------------------------------------------------------------------------------------------------------

주말인데 제가 질문이 좀 많은것 같네요..! 🙇🏻🙇🏻

2021-08-28 13:49 UTC, johngrib commented on app/src/main/java/com/codesoom/assignment/controllers/TaskController.java
> +    @Autowired
맞아요. 기왕이면 Spring 공식 문서에서도 찾아보세요. 시간이 꽤 걸릴 수도 있습니다.

2021-08-28 13:49 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +
그럼요.

2021-08-28 13:52 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +                }
좋습니다. 바로 이 맛이죠. 그런데 이렇게 해도 괜찮았을 거에요.

```java
                for (String title : TASK_TITLE) {
                    Task task = new Task();
                    task.setTitle(title);
                    taskService.createTask(task);
                }
```

2021-08-28 13:52 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +                Assertions.assertThat(taskService.getTasks()).hasSize(5);
만약 `TASK_TITLE`에 몇 개를 더 추가하면 `5`도 수정해줘야 하지 않을까요? 엄청 귀찮지 않을까요?

2021-08-28 13:52 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +            @DisplayName("검색할 Task 객체를 세팅합니다")
이 `@DisplayName`은 없어도 괜찮아요.

2021-08-28 14:10 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +        @DisplayName("tasks 리스트에 값이 존재하면")
컨트롤러에 알려져서는 안 되는 `tasks`가 리스트로 관리되고 있다는 사실이 유출되었습니다! 이건 `TaskService`의 비밀이에요.
```suggestion
        @DisplayName("등록된 할 일들이 1개 이상 있다면")
```

2021-08-28 14:10 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +            }
이건 초기화가 아니잖아요?

2021-08-28 14:10 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +            @DisplayName("tasks 리스트를 초기화합니다")
`@BeforeEach`에는 `@DisplayName`을 작성해주지 않아도 됩니다.
```suggestion
```

2021-08-28 14:10 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +    @DisplayName("detail 메소드는")
`detail` 메소드는 어디에 있나요?

2021-08-28 14:10 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +
테스트 설명문에서는 두 가지 결과를 언급하고 있어요.

- `Task` 객체를 리턴
- 200 상태코드

그런데 테스트에서는 200 만 검사하고 있군요.

2021-08-28 14:10 UTC, johngrib commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +            }
이 테스트는 무슨 일이 있어도 성공할 거에요. 반칙이죠. 테스트의 결과나 다름없는 똑같은 곳을 `willThrow`와 같이 고정해 버리면 안됩니다.

만약 형욱님이 모르는 사이에 누군가가 몰래 `getTask` 메소드를 고쳤다고 상상해 봅시다. 그런데 메소드 코드가 바뀌면서 `TaskNotFoundException`을 던지지 않는 버그가 생겼다고 합시다.

어떻게 될까요? 이 테스트를 아무리 많이 실행해도 이 테스트는 정상적으로 돌아가고 아무런 문제가 없다고 할 거에요. 그래서 이 테스트 때문에 버그를 늦게 발견하게 되거나 영영 발견하지 못할 수도 있겠죠. 그렇다면 이 테스트는 무엇을 위한 것일까요?

2021-08-28 14:11 UTC, johngrib commented
> 1. TaskService / TaskControllerTest 같은 경우를 보면 TaskControllerTest 클래스는 TaskService를 의존하여 테스트를 진행하는데 그렇다면 TaskControllerTest 클래스 파일 안에서 결국 TaskService 클래스도 같이 테스트가 적용되는게 아닌가? 라는 의문이 들었습니다. 두개 다 테스트 코드를 작성하는게 올바른 방법인 것 같은데 문득 검증하는 소스코드 유사한 면이 들었던 것 같습니다. 실무에서는 당연히 유사하다고 해도 두개의 클래스파일을 따로따로 테스트코드를 작성해주는 것이 맞는 방법이겠죠?
> 2. D-C-I 의 패턴을 적용하며 작성을 하다보니 계층적으로 볼 수 있어서 어디가 문제가 생겼는지 금방 확인이 가능한 것을 알 수 있었습니다. 하지만 그만큼 한 클래스파일에서 소스코드 라인 수가 길어지는 것을 느꼈습니다. 간단한 로직을 테스트 하는 경우에는 D-C-I패턴 말고 다른 방법을 사용하는게 나은 방법 일까요?
> 3. TaskControllerWerbTest 소스코드에서는 소스코드를 잘 작성한건지 given메소드를 올바르게 사용했는지 피드백을 듣고싶습니다.
>    수정한 TaskService와 TaskServiceCotroller 파일에 좀 더 개선할 부분이 있는지 듣고싶어요 !
>    확실히 assertEquals와 assertThat에 좀 익숙해 진 것 같습니다 !
> 
> 주말인데 제가 질문이 좀 많은것 같네요..! 🙇🏻🙇🏻

1. 오 좋은 질문입니다. 여기에서 중요한 것은 컨트롤러와 서비스가 역할이 다르다는 거에요. 지금은 로직이 단순해서 컨트롤러와 서비스가 1:1 관계를 이루고 있어요. 비유하자면 `TaskController`는 마치 `TaskService`에 씌운 비닐 랩이나 다를 바 없죠. 그게 그거 아닌가? 하는 생각까지 드는 코드입니다. 그래서 두 컴포넌트가 각기 다른 책임을 갖고 있다는 것을 잊지 않는 게 중요해요. 컨트롤러는 여러 개의 서비스를 사용해 HTTP 응답을 하기도 합니다. 그리고 서비스는 여러 개의 컨트롤러에서 활약할 수도 있어요. 이제 어느 정도 이해가 가시겠죠? 이걸 연습해보기 위해 `TaskService`를 두 개나 세 개로 쪼개보는 작업을 한번 해보세요. 지금 딱히 필요한 작업은 아니지만 의미있는 훈련은 될 거에요.
2. 물론이죠. 하지만 일관성에 손상이 가지 않도록 드물게 사용하는 것이 중요합니다.
3. 열정이 대단하세요! 코멘트를 몇 개 남겼으니 확인해주세요.

2021-08-29 00:40 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +                Assertions.assertThat(taskService.getTasks()).hasSize(5);
size 변수를 새로 생성해 주었습니다!

2021-08-29 00:41 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/application/TaskServiceTest.java
> +                }
향상된 for문을 자주 사용해 보도록 해야겠습니다 ! 훨씬 더 좋은 것 같아요

2021-08-29 00:41 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +        @DisplayName("tasks 리스트에 값이 존재하면")
수정하였습니다 !

2021-08-29 00:41 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +            }
세팅을 하여 tasks리스트에 값들을 넣어주었습니다

2021-08-29 00:42 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +    @DisplayName("detail 메소드는")
TaskControllerWeb 테스트 클래스 에서는 taskService 메소드를 바로 사용하고 있는 것을 생각하지 못하고 있었습니다 ㅠ
taskService 메소드 이름으로 변경해 주었습니다

2021-08-29 00:43 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +
tasks 객체를 검사하는 코드도 추가하였습니다.

2021-08-29 02:58 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +            }
given(taskService.getTask(INVALID_ID)) < 등록 되어 있지 않은 아이디를 검색하면
willThrow(TaskNotFoundException.class) < TaskNotFoundException 을 던진다
라는 의미로 테스트코드를 작성을 하였는데 아직 given 메소드를 어떻게 사용을 해야하는지 솔직히 잘 모르겠습니다 ㅜ

getTask 에서 메소드를 수정한다면 given 메소드에서 실패가 당연히 나오는는 줄 알고 있었습니다. 더 자세히 공부해 보겠습니다..!

2021-08-29 03:00 UTC, HyoungUkJJang commented on app/src/test/java/com/codesoom/assignment/controllers/TaskControllerWebTest.java
> +            }
/* 이런식으로 수정을 하면 될 줄 알았는데 컴파일 에러가 나오는군요..
                given(Assertions.assertThatThrownBy(() -> {
                    taskService.getTask(INVALID_ID);
                }).isInstanceOf(TaskNotFoundException.class)).willReturn(true);
                */

2021-08-29 11:47 UTC, HyoungUkJJang commented
(8/29) 피드백 반영 및 소스코드 수정
1. tasks 세팅 향상된 for문으로 수정
2. TaskControllerWebTest 메소드 이름 수정
3. BeforeEach DisplayName 삭제
4. Display 설명 수정 

------------------------------------------------------------------------------------------------------------------------

주간회고 3주차도 업로드 하였습니다 !
https://velog.io/@gudnr1451/%EC%BD%94%EB%93%9C%EC%88%A8-3%EC%A3%BC%EC%B0%A8823829-%EC%A3%BC%EA%B0%84%ED%9A%8C%EA%B3%A0

테스트 코드 작성에서 아직 이해를 확실하게 못한 부분이 있긴 하지만 그래도 테스트 코드 작성의 중요상과 그 재미를 느낄 수 있어서 좋앗습니다. 과제 풀이와 앞으로 꾸준히 작성하는 연습을 하다보면 그 이해는 자연스럽게 따라올거라 생각해요 ㅎㅎ!

오늘까지 해서 이번주도 친절하게 리뷰를 남겨주셔서 감사드립니다 !  🙇🏻

2021-08-29 12:04 UTC, johngrib approved these changes
한 주 동안 많이 발전하신 게 테스트 코드에서 보입니다. 고생 많으셨습니다. 2주 후에 또 만나요~

2021-08-29 12:06 UTC, johngrib requested changes
PR 타깃이 코드숨 메인이기 때문에 머지해드릴 수 없습니다. `Edit` 버튼을 클릭해서 PR 타깃 브랜치를 변경해 주세요.

![image](https://user-images.githubusercontent.com/1855714/131249770-238bf4e9-e951-49a2-9289-7509972df75e.png)

2021-08-29 12:17 UTC, HyoungUkJJang commented
> PR 타깃이 코드숨 메인이기 때문에 머지해드릴 수 없습니다. `Edit` 버튼을 클릭해서 PR 타깃 브랜치를 변경해 주세요.

Codesoom:HyoungUkJJang 브랜치로 변경 하였습니다 !

2021-08-29 12:50 UTC, johngrib approved these changes

2021-08-29 12:50 UTC, merged